### ISSUE TITLE
The following mods are not working and I have no idea what impact that will have on the pack.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Sadawys/multiplayer_extreme_modpack#1]
![5ziu1LT 1](https://user-images.githubusercontent.com/10351221/112021894-c3ba6b80-8aff-11eb-8ff3-ff271d0256c7.png)

Failed mods

![KVCZYcV 1](https://user-images.githubusercontent.com/10351221/112022025-e187d080-8aff-11eb-9a12-22dd4cf92a2e.png)

![qnyy1aB 1](https://user-images.githubusercontent.com/10351221/112022095-f2384680-8aff-11eb-999a-85abc123bd25.png)

![rHxKmYO 1](https://user-images.githubusercontent.com/10351221/112022155-02502600-8b00-11eb-9589-901c5a359585.png)

**Comment by Sadawys** [comment]
We upgraded the mod pack, should now work then.
This is a mod pack, missing mods will lead to missing functionalities but normally not break a new game :)
